<?php

namespace DT\Home\Middleware;

use DT\Home\Psr\Http\Message\ResponseInterface;
use DT\Home\Psr\Http\Message\ServerRequestInterface;
use DT\Home\Psr\Http\Server\MiddlewareInterface;
use DT\Home\Psr\Http\Server\RequestHandlerInterface;
use function DT\Home\route_url;
use function DT\Home\redirect;

class LoggedOut implements MiddlewareInterface
{

    /**
     * If the user is logged in, redirect to the home page.
     *
     * @param ServerRequestInterface $request The server request to be processed.
     * @param RequestHandlerInterface $handler The request handler to forward the request to.
     *
     * @return ResponseInterface The response generated by processing the request.
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler ): ResponseInterface
    {

        if ( is_user_logged_in() ) {

            return redirect( route_url() );

        }

        return $handler->handle( $request );
    }
}
