<?php

namespace DT\Home\Middleware;

use DT\Home\Psr\Http\Message\ResponseInterface;
use DT\Home\Psr\Http\Message\ServerRequestInterface;
use DT\Home\Psr\Http\Server\MiddlewareInterface;
use DT\Home\Psr\Http\Server\RequestHandlerInterface;

class UnCached implements MiddlewareInterface {
    /**
     * Sets the Cache-Control header to "uncached".
     *
     * @param ServerRequestInterface $request The request to process.
     * @param RequestHandlerInterface $handler The request handler to use.
     *
     * @return ResponseInterface The response generated by the request handler.
     */
    public function process( ServerRequestInterface $request, RequestHandlerInterface $handler ): ResponseInterface
    {
	    header( 'Cache-Control: uncached' );

		return $handler->handle( $request );
    }
}
